import turtle

turtle.pensize(2)

turtle.circle(40)
turtle.penup()
turtle.goto(-90, 0)
turtle.color('blue')
turtle.pendown()
turtle.circle(40)
turtle.penup()
turtle.goto(-45, -40)
turtle.color('yellow')
turtle.pendown()
turtle.circle(40)
turtle.penup()
turtle.goto(90, 0)
turtle.color('red')
turtle.pendown()
turtle.circle(40)
turtle.penup()
turtle.goto(45, -40)
turtle.color('green')
turtle.pendown()
turtle.circle(40)
